name: CI

on:
  push:
    branches:
      - 'main'
      - '*.*'
      - '!*backport*'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      toxdeps: tox-pypi-filter
      envs: |
        - linux: py312
      coverage: 'codecov'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      toxdeps: tox-pypi-filter
      envs: |
        - macos: py311
        - windows: py310
      coverage: 'codecov'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    needs: [tests]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      toxdeps: tox-pypi-filter
      envs: |
        - linux: build_docs-gallery
          python-version: '3.12'
      libraries: |
        apt:
          - graphviz

  publish:
    # Build wheels when pushing to any branch except main
    # publish.yml will only publish if tagged ^v.*
    if: |
      (
        github.event_name != 'pull_request' && (
          github.ref_name != 'main' ||
          github.event_name == 'workflow_dispatch'
        )
      ) || (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'Run publish')
      )
    needs: [tests]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@main
    with:
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst --pyargs synthesizAR'
      submodules: false
      python-version: '3.12'
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
